config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order("created_at DESC")
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterCloneRor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if flash[:notice] %>
        <div class="notification is-primary global-notification">
          <p class="notice"><%= notice %></p>
        </div>
  <% end %>
  <% if flash[:alert] %>
        <div class="notification is-danger global-notification">
          <p class="alert"><%= alert %></p>
        </div>
  <% end %>

  <nav class="navbar is-info">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do%>
          <h1 class="title is-5">Twitter</h1>
      <% end%>
      <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
      </div>
    </div> 

    <div id="navbarExample" class = "navbar-menu">
        <div class="navbar-end">
            <div class="field is-grouped">
                <p class="control mine">
                <%= link_to 'New Tweet', new_tweet_path, class: "button is-info is-inverted" %>
                </p>
                <p class="control button is-info is-inverted">Sign Up</p>
            </div>
        </div>
    </div>
  </nav>
  

    <%= yield %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<div class="column is-half">
    <article class="media box">
        <figure class="media-left">
            <p class="image is-64x64">
                <img src="https://bulma.io/images/placeholders/64x64.png">
            </p>
        </figure>
        <div class="media-content">

        </div>
    </article>
</div>

<% @tweets.each do |tweet| %>
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-64x64">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
                <div class="media-content">
                    <div class="content">
                        <strong>Andy Leverenz</strong><br />
                        <small>@webcrunch</small>
                        <p><%= tweet.tweet %></p>
                    </div>
                    <nav class="level">
                        <div class="level-left is-mobile">
                            <%= link_to tweet, class: "level-item" do %>
                                <span class="icon">
                                    <i class="fa fa-link" aria-hidden="true"></i>
                                </span>
                            <% end %>
                            <%= link_to edit_tweet_path(tweet), class: "level-item" do %>
                                <span class="icon">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>
                                </span>
                            <% end %>
                            <%= link_to tweet, method: :delete,  data: {confirm: "are you sure you want to delete this tweet?"} do %>
                                <span class="icon">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </span>
                            <% end %>
                        </div>
                    </nav>
                </div>
            </div>
        </article>
    </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweet %>
    <%= form.text_area :tweet %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<section class="section">
  <div class="container">
      <div class="columns">
      <%= render 'feed' %>
      </div>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>